CREATE TABLE urls (
    id       BIGINT AUTO_INCREMENT PRIMARY KEY,
    code     VARCHAR(16) UNIQUE,
    url      VARCHAR(4096) NOT NULL,
    clicks   INT NOT NULL DEFAULT 0,
    created  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
